SELECT r.REVIEW_ID, r.ACCOUNTID, r.STOREID, r.REVIEWCONTENT, r.WRITEDATE, r.TASTELEVEL, 
r.PRICELEVEL, r.SERVICELEVEL, r.MOODLEVEL,r.CONVENIENCELEVEL r.LIKECOUNT, r.HATECOUNT, ifnull(l.ISLIKE,0) as 'ISLIKE'
FROM REVIEW r LEFT JOIN (SELECT * FROM LIKEHATE  WHERE ACCOUNT_ID = 1) l
ON(r.REVIEW_ID = l.REVIEW_ID AND r.ACCOUNTID = l.ACCOUNT_ID)
WHERE r.STOREID = 1;
commit;
